Chamabora/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from authentication.views import showFirebaseJS

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('user/', include('authentication.urls')),
    path('wallet/', include('wallet.urls')),
    path('dashboard/', include('Goals.urls')),
    path('load_money/', include('mpesa_integration.urls')),
    path('withdraw/', include('pyment_withdraw.urls')),
    path('user-dash/', include('Dashboard.urls')),
    path('notifications/', include('notifications.urls')),
    path('send/', include('notifications.urls')),
    path('firebase-messaging-sw.js', showFirebaseJS, name="show_firebase_js"),
    path('subscriptions/', include('subscriptions.urls')),
    path('chamas-bookeeping/',include('chamas.urls')),
    path('bot/',include('bot.urls'))
]


if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

bot/urls.py
from django.urls import path
from . import views

app_name = 'bot'
urlpatterns = [
    path('webhook/',views.receive_message,name='infobip_webhook'),
    path('reports/<int:chama_id>/',views.bot_records,name='bot-records'),
    path('contributions/approve/<int:chama_id>/',views.approve_contribution,name='approve-contribution'),
    path('contributions/reject/<int:chama_id>/',views.flag_contribution,name='flag-contribution'),

    path('loans/approve/<int:chama_id>/',views.approve_loan,name='approve-loan'),
    path('loans/reject/<int:chama_id>/',views.flag_loan,name='flag-loan'),
    path('fines/approve/<int:chama_id>/',views.approve_fine,name='approve-fine'),
    path('fines/reject/<int:chama_id>/',views.flag_fine,name='flag-fine'),
    path('members/approve/<int:chama_id>/',views.approve_member,name='approve-member'),
    path('members/reject/<int:chama_id>/',views.flag_member,name='flag-member')

]

chamas/urls.py
from django.urls import path
from . import views

app_name = 'chamas'
urlpatterns = [
    path('chamas/',views.chamas,name='chamas'),
    path('new-chama-form/',views.new_chama_form,name='new-chama-form'),
    path('new-chama/',views.create_chama,name='new-chama'),
    path('your-chamas/',views.your_chamas,name='your-chamas'),
    path('create-new-chama-type/',views.create_chama_type,name='new-chama-type'),
    
    path('add-member/',views.add_member_to_chama,name='add-member'),
    path('edit-member/',views.edit_member_in_chama,name='edit-member'),
    path('members/<int:chama_id>/',views.members,name='members'),
    path('remove-member-from-chama/<int:member_id>/<int:chama_id>/',views.remove_member_from_chama,name='remove-member-from-chama'),
    path('member-detail/<int:chama_member_id>/<int:group>/',views.member_details,name='member-details'),
    path('ascertain-member-role/<int:chama_id>/',views.ascertain_member_role,name="ascertain-member-role"),

    path('chama-dashboard/<int:chama_id>/',views.dashboard,name='chama-dashboard'),
    path('upload-document/<int:chama_id>/',views.upload_document,name='upload-document'),
    path('download-document/<int:chama_id>/<int:document_id>/',views.download_document,name='download-document'),
    path('delete-document/<int:chama_id>/<int:document_id>/',views.delete_document,name='delete-document'),

    path('contributions/<int:chama_id>/',views.contributions,name='contributions'),
    path('create-contribution-record/<int:chama_id>/',views.create_contribution_record,name='create-contribution-record'),
    path('create-contribution/<int:chama_id>/',views.create_contribution,name='create-contribution'),
    path('retrieve-contribution/<int:chama_id>/',views.contributions_details,name='contribution-details'),
    path('update-contribution/<int:chama_id>/<int:contribution_id>/',views.update_contribution,name='update-contribution'),
    path('get-contribution/<int:chama_id>/<int:contribution_id>/',views.get_contribution_details,name='get-contribution-details'),
    path('pay-contribution/<int:contribution_id>/',views.pay_contribution,name='pay-contribution'),

    path('chama-loans/<int:chama_id>/',views.chama_loans,name='chama-loans'),
    path('create-loan-type/<int:chama_id>/',views.create_loan_type,name='create-loan-type'),
    path('issue-loan/<int:chama_id>/',views.issue_loan,name='issue-loan'),
    path('apply-loan/<int:chama_id>/',views.apply_loan,name='apply-loans'),
    path('approve-loan/<int:chama_id>/<int:loan_id>/',views.accept_loan_request,name='accept-loan-request'),
    path('decline-loan/<int:chama_id>/<int:loan_id>/',views.decline_loan,name='decline_loan'),
    path('update-loan/<int:loan_id>/',views.update_loan,name='update-loan'),


    path('chama-fines/<int:chama_id>/',views.chama_fines,name='chama-fines'),
    path('create-fine-type/<int:chama_id>/',views.create_fine_type,name='create-fine-type'),
    path('impose-fine/',views.impose_fine,name='impose-fine'),
    path('update-fine/',views.update_fine,name='update-fine'),
    path('fine-contribution/<int:contribution_id>/',views.fine_contribution,name='fine-contribution'),


    path('chama-expenses/<int:chama_id>/',views.expenses,name='chama-expenses'),
    path('create-expense/<int:chama_id>/',views.create_expense,name='create-expense'),

    path('chama-finances/<int:chama_id>/',views.finances,name='finances'),
    path('create-saving/<int:chama_id>/',views.create_saving,name='create-saving'),
    path('create-investment/<int:chama_id>/',views.create_investment,name='create-investment'),
    path('create-income/<int:chama_id>/',views.create_income,name='create-income'),

    path('chama-reports/<int:chama_id>/',views.reports,name='reports'),
    path('download-full-loan-report/<int:chama_id>/',views.download_loan_report,name='download-loan-report'),
    path('download-loan-repayment-schedule/<int:chama_id>/',views.download_loan_repayment_schedule,name='download-loan-repayment-schedule'),
    path('download-group-investment-income/<int:chama_id>/',views.download_group_investment_income,name='download-group-investment-income'),
    path('download-member-investment-income/<int:chama_id>/',views.download_member_investment_income,name='download-member-investment-income'),
    path('download-my-investment-income/<int:chama_id>/',views.download_my_investment_income,name='download-my-investment-income'),
    path('download-group-investments/<int:chama_id>/',views.download_group_investments,name='download-group-investments'),
    path('download-individual-saving-report/<int:chama_id>/',views.download_individual_saving_report,name='download-individual-saving-report'),
    path('download-group-saving-report/<int:chama_id>/',views.download_group_saving_report,name='download-group-saving-report'),
    path('download-my-saving-report/<int:chama_id>/',views.download_my_saving_report,name='download-my-saving-report'),
    path('download-group-contributions-report/<int:chama_id>/<int:contribution_id>/',views.download_group_contributions_report,name='download-group-contributions-report'),
    path('download-member-contributions-report/<int:chama_id>/<int:member_id>/<int:scheme_id>/',views.download_member_contribution_report,name='download-member-contribution-report'),
    path('download-member-contributions-report/<int:chama_id>/',views.download_member_contribution_report,name='download-member-contribution-report-query'),
    path('download-collected-fines-report/<int:chama_id>/',views.download_collected_fine_report,name='download-collected-fines-report'),
    path('download-uncollected-fines-report/<int:chama_id>/',views.download_uncollected_fines_report,name='download-uncollected-fines-report'),
    path('download-chama-cashflow-report/<int:chama_id>/',views.download_cashflow_report,name='download-chama-cashflow-report'),
    path('download-member-cashflow-report/<int:chama_id>/<int:member_id>/',views.download_member_cashflow_report,name='download-member-cashflow-report'),
    path('download-my-cashflow-report/<int:chama_id>/',views.download_my_cashflow_report,name='download-my-cashflow-report'),
    path('download-expense-report/<int:chama_id>/',views.download_expense_report,name='download-expense-report'),

    path('chama-notifications/<int:chama_id>/',views.notifications,name='notifications'),
    path('new-notification-type/<int:chama_id>/',views.create_notif_type,name='create-notification-type'),
    path('new-notification/<int:chama_id>/',views.create_notif,name='create-notification'),

    path('get_user_role/', views.get_user_role, name='get_user_role'),
    path('get-member-cashflow-data/<int:chama_id>/', views.get_member_cashflow_data, name='get-member-cashflow-data'),
    path('get-loan-repayment-schedule/<int:chama_id>/', views.get_loan_repayment_schedule, name='get-loan-repayment-schedule'),
    path('get-member-contributions-data/<int:chama_id>/', views.get_member_contributions_data, name='get-member-contributions-data'),
    path('get-group-investment-income-data/<int:chama_id>/', views.get_group_investment_income_data, name='get-group-investment-income-data'),
    path('get-member-investment-income-data/<int:chama_id>/', views.get_member_investment_income_data, name='get-member-investment-income-data'),
    path('get-my-investment-income-data/<int:chama_id>/', views.get_my_investment_income_data, name='get-my-investment-income-data'),
    path('get-individual-saving-data/<int:chama_id>/', views.get_individual_saving_data, name='get-individual-saving-data'),
    path('get-group-saving-data/<int:chama_id>/', views.get_group_saving_data, name='get-group-saving-data'),
    path('get-my-saving-data/<int:chama_id>/', views.get_my_saving_data, name='get-my-saving-data'),
    path('get-collected-fines-data/<int:chama_id>/', views.get_collected_fines_data, name='get-collected-fines-data'),
    path('get-unpaid-fines-data/<int:chama_id>/', views.get_unpaid_fines_data, name='get-unpaid-fines-data'),
    path('get-expenses-data/<int:chama_id>/', views.get_expenses_data, name='get-expenses-data'),
    
    # My Chamas view
    path('my-chamas/', views.my_chamas_view, name='my-chamas'),

]

subscriptions/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('plans/<int:chama_id>/', views.subscription_chama, name='subscription_chama'),
    path('plans/', views.subscription_plans, name='subscription_plans'),
    path('start-trial', views.start_trial, name='start_trial'),
    path('subscribe/', views.subscribe, name='subscribe'),

    path('mpesa-express/', views.mpesa_express, name='mpesa_express'),
    path('lnmo-callback/', views.lnmo_callback, name='lnmo_callback'),
    path('subscription-waiting/', views.subscription_waiting, name='subscription_waiting'),

    path('lipa_na_mpesa/', views.lipa_na_mpesa_online, name='lipa_na_mpesa'),

    path('processing/', views.subscription_waiting, name='subscription_waiting'),
    path('processing/<str:signature>', views.subscription_waiting, name='subscription_waiting_with_signature'),

    path('processing/<str:signature>/status/', views.subscription_status, name='subscription_status'),
    path('success/', views.subscription_success, name='subscription_success'),

    path('failed/', views.subscription_error, name='subscription_error'),
    path('failed/<str:error>', views.subscription_error, name='subscription_failed'),
    path('webhook/<str:signature>', views.subscription_webhook, name='subscription_webhook'),
]

subscriptions/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import ExpressionWrapper, F, FloatField
from django.utils import timezone
from datetime import timedelta
from chamas.models import Chama

class PaymentDetail(models.Model):
    amount = models.DecimalField(max_digits=10, decimal_places=2, null=True)
    mpesa_receipt_number = models.CharField(max_length=100, null=True)
    checkout_request_id = models.CharField(max_length=500, null=True)
    chama_subscription = models.ForeignKey("ChamaSubscription", on_delete=models.SET_NULL, blank=True, null=True)
    transaction_date = models.DateTimeField(null=True)
    phone_number = models.CharField(max_length=20, null=True)
    result_desc = models.CharField(max_length=255, null=True)
    payment_status = models.CharField(max_length=20, choices=[
        ('PENDING', 'Pending'),
        ('SUCCESS', 'Success'),
        ('FAILED', 'Failed'),
    ], default='PENDING')
    possible_duplicate = models.BooleanField(default=False) 
class Tax(models.Model):
    name = models.CharField(max_length=100,blank=True,null=True)
    rate = models.DecimalField(max_digits=10, decimal_places=2,default=0.20, help_text="Tax rate as a percentage")

    def __str__(self):
        return f"{self.name} ({self.rate}%)"

class SubscriptionPlan(models.Model):
    name = models.CharField(max_length=100, default="Standard Plan")
    period_name = models.CharField(max_length=100, blank=True, null=True, default="year")
    price = models.DecimalField(max_digits=6, decimal_places=2, default=2000.00)
    trial_duration = models.DurationField(default=timedelta(days=14))
    period_duration = models.DurationField(default=timedelta(days=365))
    grace_period = models.DurationField(default=timedelta(days=2))
    taxes = models.ManyToManyField(Tax, related_name='subscription_plans_tax', blank=True)
    def __str__(self):
        return self.name

    def get_total_amount(self):
        plan_price = float(self.price)
        all_tax = float(0.0)
        taxes = self.taxes.all().annotate(tax_price=ExpressionWrapper(F('rate') * plan_price,
                                                                      output_field=FloatField()
                                                                      ))
        for tax in taxes:
            all_tax = all_tax + (plan_price * float(tax.rate))
        return plan_price + round(all_tax,0)

class ChamaSubscription(models.Model):
    chama = models.ForeignKey(Chama, on_delete=models.CASCADE)
    start_date = models.DateTimeField(auto_now_add=True)
    end_date = models.DateTimeField()
    plan = models.ForeignKey(SubscriptionPlan, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    payment_details = models.ForeignKey(PaymentDetail, on_delete=models.SET_NULL,blank=True, null=True)
    phone = models.CharField(max_length=25, blank=True, null=True)

    def __str__(self):
        return f'{self.chama.name} - {self.plan.name} - {self.user.username if self.user else ""}'

    def is_active(self):
        now = timezone.now()
        return now < self.end_date + self.plan.grace_period

    def is_trial(self):
        now = timezone.now()
        return now < self.start_date + self.plan.trial_duration and (self.end_date - now).days < self.plan.trial_duration.days

    def remaining_trial_days(self):
        if self.is_trial():
            return (self.start_date + self.plan.trial_duration - timezone.now()).days
        return 0

subscriptions/templates/subscriptions/base_pricing.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Pricing{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/tailwindcss@2.2.19/dist/tailwind.min.css" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.2/css/all.min.css" integrity="sha512-SnH5WK+bZxgPHs44uWIX+LLJAJ9/2PkPKZ5QiAj6Ta86w+fsb2TkcmfRyVX3pBnMFcV7oQPJkl9QevSCWr3W6A==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    {% block head %}{% endblock %}
    {% block styles %}{% endblock %}
    <style>
        @tailwind base;
        @tailwind components;
        @tailwind utilities;

        @layer utilities {
            .bg-primary {
                background-color: #2191a5;
            }
            .text-primary {
                color: #2191a5;
            }
            .border-primary {
                border-color: #2191a5;
            }
        }
    </style>
</head>
<body class="bg-gray-100">
    {% comment %} <header class="bg-white py-4 shadow">
    </header> {% endcomment %}

    <div class="container mx-auto py-8 px-5">
        {% block content %}{% endblock %}
    </div>

    {% comment %} <footer class="bg-gray-800 text-white py-4">
    </footer> {% endcomment %}

    {% block scripts %}{% endblock %}
</body>
</html>

subscriptions/templates/subscriptions/error.html
{% extends 'subscriptions/base_pricing.html' %}

{% block title %}Subscription Error{% endblock %}

{% block content %}
<div class="max-w-lg mx-auto bg-white rounded-lg shadow-md overflow-hidden">
    <div class="px-6 py-8">
        <div class="text-red-600 text-6xl text-center mb-6">
            <i class="fas fa-exclamation-circle"></i>
        </div>
        <h2 class="text-2xl font-semibold text-gray-800 text-center mb-4">Subscription Failed!</h2>
        <p class="text-center">We're sorry, but there was an issue processing your payment. Please try again later.</p>
        {% if error %}
            <p class="text-center">Reason: {{ error }}</p>
        {% endif %}
        {%if request.GET.message%}
        <p class="text-center">Reason: {{ request.GET.message }}</p>
        {%endif%}
        <div class="mt-6 text-center">
            <a href="{% url 'subscription_plans' %}" class="text-green-600 hover:underline">Back to Subscription Plans</a>
        </div>
    </div>
</div>
{% endblock %}

subscriptions/templates/subscriptions/plans.html
{% extends 'subscriptions/base_pricing.html' %}

{% block title %}Upgrade to {{ plan.name }}{% endblock %}

{% block content %}
<div class="max-w-lg mx-auto bg- rounded- shadow- overflow-hidden">
    <div class="px-6 py-8">
        <h2 class="text-2xl font-semibold text-gray-800 text-center mb-4">
            {% if not current_chama_subscription %}
                Try
            {% else %}
                Upgrade to
            {% endif %}

            {{ plan.name }}

            {% if not current_chama_subscription %}
                for 14 days
            {% endif %}
        </h2>
        <div class="flex flex-col items-center justify-center">
            <div class="bg-green-600 text-white rounded-lg p-8 w-full">
                <h3 class="text-3xl font-semibold mb-2">{{ plan.name }}</h3>
                <hr class="my-5 border-green-100"/>
                <p class="text-xl font-semibold mb-4">Price: KES {{ plan.get_total_amount }}/{{plan.period_name}}</p>
                <ul class="text-md text-gray-100">
                    <li class="mb-2">- Access to exclusive features</li>
                    <li class="mb-2">- Priority support</li>
                    <li class="mb-2">- Better experience experience</li>
                </ul>
                <div 
                class="flex flex-col gap-y-2
                mt-6">
                    {% if not current_chama_subscription %}
                        <a href="{% url 'start_trial' %}" class="block bg-white text-green-600 hover:bg-green-100 hover:text-green-800 font-semibold py-2 px-4 rounded-md shadow-md transition duration-300 ease-in-out text-center">Start 14 day trial</a>
                    {% elif is_active and is_trial and expiration_date %}
                        <a href="{% url 'subscribe' %}" class="block bg-white text-green-600 hover:bg-green-100 hover:text-green-800 font-semibold py-2 px-4 rounded-md shadow-md transition duration-300 ease-in-out text-center">Upgrade Now</a>
                    {% elif is_active and not is_trial and expiration_date %}
                        <a href="{% url 'chamas:chama-dashboard' chama_id %}" class="block bg-white text-green-600 hover:bg-green-100 hover:text-green-800 font-semibold py-2 px-4 rounded-md shadow-md transition duration-300 ease-in-out text-center">View Dashboard</a>
                    {% else %}
                        <a href="{% url 'subscribe' %}" class="block bg-white text-red-600 hover:bg-red-100 hover:text-red-800 font-semibold py-2 px-4 rounded-md shadow-md transition duration-300 ease-in-out text-center">Renew Subscription</a>
                    {% endif %}
                </div>
            </div>
            <div 
            class="flex flex-col gap-y-2
            mt-6">
                {% if is_active and is_trial and expiration_date %}
                    <p class="text-center text-red-600">Your trial expires on {{ expiration_date|date:"F j, Y" }}</p>
                    <a href="{% url 'chamas:chama-dashboard' chama_id %}" class="block text-green-600  hover:text-green-800 font-semibold py-2 px-4 
                    transition duration-300 ease-in-out text-center"><< Back to Dashboard </a>
                {% elif is_active and not is_trial and expiration_date %}
                    <p class="text-center text-red-600">Your subscription expires on {{ expiration_date|date:"F j, Y" }}</p>
                {% else %}
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

subscriptions/templates/subscriptions/subscribe.html
{% extends 'subscriptions/base_pricing.html' %}

{% block title %}Checkout{% endblock %}


{% block content %}
<div class="max-w-lg mx-auto bg-white rounded-lg shadow-md overflow-hidden">
    <div class="px-6 py-8">
        <h2 class="text-2xl font-semibold text-gray-800 text- mb-4">Complete Payment <span class="text-green-600">({{plan.name}})</span> </h2>
        <form 
        action="{% url 'subscribe' %}" method="post">
            {% csrf_token %}
            <div class="mb-4">
                <label for="phone" class="block text-gray-700 text-sm font-bold mb-2">Mpesa Phone Number</label>
                <input 
                type="text" 
                id="phone" 
                name="phone" 
                placeholder="Enter your mpesa phone number"
                class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
                value="+254">

                <input type="hidden" name="amount" id="amount" value={{receipt_total_amount}}>
                <input type="hidden" name="user_id" id="user_id" value={{user_id}}>
                <input type="hidden" name="chama_id" id="chama_id" value={{chama_id}}>
                <input type="hidden" name="plan_id" id="plan_id" value={{plan_id}}>
            </div>


            <div class="flex flex-col">
                <div
                class="flex flex-row justify-between">
                    <p class="text- py-2"><strong>Amount:</strong></p>
                    <p class="text- py-2">KES {{ receipt_amount }}</p>
                </div>
                {% for tax in  taxes %}
                <div
                class="flex flex-row justify-between">
                    <p class="text- py-2"><strong>{{ tax.name }}:</strong></p>
                    <p class="text- py-2">KES {{ tax.tax_price}} </p>
                </div>
                {% endfor %}
                <div
                class="flex flex-row justify-between border-t">
                    <p class="text- py-2"><strong>Total Amount:</strong></p>
                    <p class="text- py-2">KES {{ receipt_total_amount }}</p>
                </div>
            </div>
        
            <div class="flex items-center justify-center mt-6">
                <button type="submit" class="bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline">Pay with M-Pesa</button>
            </div>
        </form>

         <!-- Loading Animation -->
        <div id="loading" class="hidden mt-4">
            <div class="spinner-border text-blue-500"></div>
            <p class="text-sm mt-2">Processing payment...</p>
        </div>
    </div>
</div>
{% endblock %}

subscriptions/templates/subscriptions/success.html
{% extends 'subscriptions/base_pricing.html' %}
{% load static %}
{% block title %}Payment Invoice{% endblock %}

{% block content %}
    <!-- CSS to hide the Back to Dashboard link when printing -->
<style>
    @media print {
        .no-print {
            display: none;
        }
    }
</style>
<script src="https://cdnjs.cloudflare.com/ajax/libs/html2pdf.js/0.9.3/html2pdf.bundle.min.js"></script>

<div class="max-w-2xl mx-auto bg-white rounded-lg shadow-md overflow-hidden p-8">
    <!-- Header: M-PESA Logo and Invoice Title -->
    <!-- Payment Success Message -->
    <h3 class="text-lg font-semibold text-green-700 mb-4 no-print">Payment Successful!</h3>
    <p class="mb-8 no-print">Thank you for your payment with M-PESA. Below are your payment details:</p>
    <div class="flex justify-between items-center mb-8">
        <img src="{% static 'images/offcanvas_logo.png' %}" alt="Chamaspace Logo" class="h-12">
        <h2 class="text-2xl font-semibold text-gray-800">Invoice</h2>
    </div>

    <!-- Payment Details -->
    <div class="border-t border-b border-gray-300 py-4 mb-8">
        <div class="flex justify-between">
            <span class="font-medium">Total Amount Paid:</span>
            <span class="text-xl font-bold text-green-600">KES {{ payment_details.amount }}</span>
        </div>
        <div class="flex justify-between mt-2">
            <span>Phone Number:</span>
            <span>+{{ payment_details.phone_number }}</span>
        </div>
    </div>

    <!-- Transaction Information -->
    <div class="bg-gray-50 rounded-lg p-4 mb-8">
        <div class="flex justify-between">
            <span>Date:</span>
            <span>{{ payment_details.transaction_date }}</span>
        </div>
        <div class="flex justify-between mt-2">
            <span>Receipt No:</span>
            <span>{{ payment_details.mpesa_receipt_number }}</span>
        </div>
        <div class="flex justify-between mt-2">
            <span>Payment Status:</span>
            <span>{% if payment_details.payment_status == "SUCCESS" %}PAID{% endif %}</span>
        </div>
    <div class="flex justify-between mt-2">
            <span>Chama:</span>
            <span>{{ payment_details.chama_subscription.chama.name }}</span>
        </div>
        <div class="flex justify-between mt-2">
            <span>Plan:</span>
            <span>{{ payment_details.chama_subscription.plan.name }}</span>
        </div>
        <div class="flex justify-between mt-2">
            <span>Expire at:</span>
            <span>{{ payment_details.chama_subscription.end_date }}</span>
        </div>
    </div>

    <!-- Back to Dashboard and Download Button -->
    <div class="flex justify-between items-center">
        <a href="{% url 'chamas:chama-dashboard' chama_id %}" class="text-green-600 no-print hover:underline">Back to Dashboard</a>
        <button id="download" class="bg-green-600 text-white px-4 py-2 no-print rounded-lg hover:bg-green-700">Download Invoice</button>
    </div>
</div>

<!-- Add JavaScript for downloading the invoice -->
<!--?<script>-->
<!--?    document.getElementById('download').addEventListener('click', function() {-->
<!--?        window.print();  // This will trigger the browser's print dialog which you can use to download as PDF-->
<!--?    });-->
<!--?</script>-->
<script>
    document.getElementById('download').addEventListener('click', function() {
        // Get elements with the 'no-print' class
        var noPrintElements = document.querySelectorAll('.no-print');

        // Hide the elements with 'no-print' class
        noPrintElements.forEach(function(element) {
            element.style.display = 'none';
        });

        // Generate the PDF
        var element = document.body;  // You can specify a particular element if needed
        var fileName="invoice_{{ payment_details.mpesa_receipt_number }}.pdf";
        html2pdf().from(element).save(fileName).then(function() {
            // Restore the 'no-print' elements after PDF generation
            noPrintElements.forEach(function(element) {
                element.style.display = '';
            });
        });
    });
</script>

{% endblock %}

subscriptions/templates/subscriptions/waiting.html
{% extends 'subscriptions/base_pricing.html' %}

{% block title %}Waiting for Payment{% endblock %}

{% block content %}
<div class="max-w-lg mx-auto bg-white rounded-lg shadow-md overflow-hidden">
    <div class="px-6 py-8">
        <div class="text-green-400 text-6xl text-center mb-6">
            <i class="fas fa-hourglass-half"></i>
        </div>

        <h2 class="text-2xl font-semibold text-gray-800 text-center mb-4">Waiting for payment</h2>
        <p class="text-center text-">A payment prompt will be sent to your phone momentarily!</p>
        <p class="text-center text- my-2 text-red-600"> Please complete the payment and wait on the page while we process your payment</p>

        <div class="flex justify-center items-center space-x-2 mt-5">
            <div class="w-3 h-3 bg-gray-600 rounded-full animate-bounce"></div>
            <div class="w-3 h-3 bg-gray-600 rounded-full animate-bounce" style="animation-delay: 0.1s;"></div>
            <div class="w-3 h-3 bg-gray-600 rounded-full animate-bounce" style="animation-delay: 0.2s;"></div>
        </div>
    </div>
</div>
{% endblock %}


{% block scripts %}
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function() {
        var paymentSettled = false; 

        $(window).on('beforeunload', function() {
            return 'Please wait while we process your payment.';
        });

        $(window).on('beforeunload', function(event) {
            if (!paymentSettled) {
                var message = 'Please wait while we process your payment.';
                event.returnValue = message;
                return message;
            }
        });
        

        function checkPaymentStatus() {
            $.ajax({
                url: '{% url 'subscription_status' signature=signature %}',  
                type: 'GET',
                success: function(response) {
                    paymentSettled = response.settled
                    if(response.success){
                        url = '{% url "subscription_success" %}'
                        window.history.pushState({}, '', url);
                        window.location.replace(url);
                    } 
                    if(!response.success && response.message){
                        var error = response.message;
                        url = '/subscriptions/failed/' + encodeURIComponent(error)
                        window.location.replace(url)
                    } 
                },
                error: function(xhr, status, error) {
                    console.error('Error:', error);
                }
            });
        }
        setInterval(checkPaymentStatus, 5000);
    });
</script>
{% endblock %}